name: Kafka Topic Request

on:
  workflow_dispatch:
    inputs:
      client:
        description: 'Nom du client'
        required: true
      environnement:
        description: 'Environnement (dev/staging/production)'
        required: true
      event:
        description: 'Type d’événement (ex: transaction, paiement, etc.)'
        required: true
      version:
        description: 'Version du topic (ex: v1)'
        required: true
      retention:
        description: 'Durée de rétention (ex: 7d, 30d)'
        required: true
      partitions:
        description: 'Nombre de partitions'
        required: true

jobs:
  create-issue:
    runs-on: self-hosted
    steps:
    - name: Générer le contenu de l'issue
      run: |
        echo "#KafkaTopicRequest" > issue-body.md
        echo "client: ${{ inputs.client }}" >> issue-body.md
        echo "environnement: ${{ inputs.environnement }}" >> issue-body.md
        echo "event: ${{ inputs.event }}" >> issue-body.md
        echo "version: ${{ inputs.version }}" >> issue-body.md
        echo "retention: ${{ inputs.retention }}" >> issue-body.md
        echo "partitions: ${{ inputs.partitions }}" >> issue-body.md

    - name: Créer une issue Kafka
      uses: peter-evans/create-issue-from-file@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Création topic Kafka pour ${{ inputs.client }}"
        content-filepath: issue-body.md
        labels: |
          kafka
          auto-generated
